/**
 * 代码生成器
 * 将 DSL 转换为标准 React TSX 代码
 *
 * 支持：
 * - 内联样式模式（默认）
 * - CSS 文件分离模式
 * - framer-motion 动画导出
 */

import type { ComponentNode, CanvasConfig } from '@/types';
import { componentRegistry } from '@store/componentRegistry';

/**
 * 导出模式
 */
export type ExportMode = 'inline' | 'css';

/**
 * 导出选项
 */
export interface ExportOptions {
  mode?: ExportMode;
  includeAnimation?: boolean;
}

/**
 * 代码生成结果
 */
export interface CodeGenResult {
  tsx: string;
  css?: string;
  dependencies?: string[];
}

/**
 * 代码生成器类
 * 负责将组件树和画布配置转换为可执行的 React TSX 代码
 */
export class CodeGenerator {
  /**
   * 生成完整的代码
   * @param components 组件树数组
   * @param config 画布配置
   * @param options 导出选项
   * @returns 代码生成结果
   */
  generateCode(
    components: ComponentNode[],
    config: CanvasConfig,
    options: ExportOptions = {}
  ): CodeGenResult {
    const { mode = 'inline', includeAnimation = true } = options;

    // 如果画布为空，返回空组件模板
    if (components.length === 0) {
      return {
        tsx: this.generateEmptyTemplate(config, { includeAnimation }),
      };
    }

    // 生成 imports（包括组件定义的 imports）
    const needsFramerMotion = includeAnimation && components.some(c => c.animation);
    const imports = this.generateImports(components, { includeAnimation: needsFramerMotion });

    // 生成 CSS（仅 CSS 模式）
    let css: string | undefined;
    if (mode === 'css') {
      css = this.generateCSS(components);
    }

    // 生成组件代码
    const componentCode = this.generateComponent(components, config, {
      mode,
      includeAnimation,
    });
    const exports = this.generateExports();

    return {
      tsx: `${imports}\n\n${componentCode}\n\n${exports}`,
      css,
    };
  }

  /**
   * 生成完整的 TSX 文件代码（兼容旧 API）
   * @param components 组件树数组
   * @param config 画布配置
   * @returns 完整的 TSX 代码字符串
   */
  generateTSXCode(components: ComponentNode[], config: CanvasConfig): string {
    return this.generateCode(components, config, {}).tsx;
  }

  /**
   * 生成 CSS 文件内容
   * @param components 组件树数组
   * @returns CSS 文件内容
   */
  generateCSS(components: ComponentNode[]): string {
    const lines: string[] = [
      `/* Generated by DragBuilder */`,
      `/* 可根据需要合并到项目的 CSS 文件中 */`,
      ``,
    ];

    // 按 zIndex 排序
    const sortedComponents = [...components].sort((a, b) => a.position.zIndex - b.position.zIndex);

    for (const component of sortedComponents) {
      const def = componentRegistry.get(component.type);
      if (def?.codeGen.generateCSS) {
        lines.push(def.codeGen.generateCSS(component));
        lines.push('');
      } else {
        // 使用默认 CSS 生成
        lines.push(this.generateComponentCSS(component));
        lines.push('');
      }
    }

    return lines.join('\n');
  }

  /**
   * 生成单个组件的 CSS
   */
  private generateComponentCSS(component: ComponentNode): string {
    const { position, styles } = component;
    const className = this.generateUniqueClassName(component);

    const lines: string[] = [];
    lines.push(`.${className} {`);

    // Position styles
    lines.push(`  position: absolute;`);
    lines.push(`  left: ${position.x}px;`);
    lines.push(`  top: ${position.y}px;`);
    lines.push(`  width: ${position.width}px;`);
    lines.push(`  height: ${position.height}px;`);
    lines.push(`  z-index: ${position.zIndex};`);

    // Visual styles
    if (styles.backgroundColor) {
      lines.push(`  background-color: ${styles.backgroundColor};`);
    }
    if (styles.borderColor && styles.borderWidth !== undefined) {
      lines.push(`  border: ${styles.borderWidth}px solid ${styles.borderColor};`);
    }
    if (styles.borderRadius !== undefined) {
      lines.push(`  border-radius: ${styles.borderRadius}px;`);
    }
    if (styles.textColor) {
      lines.push(`  color: ${styles.textColor};`);
    }
    if (styles.fontSize !== undefined) {
      lines.push(`  font-size: ${styles.fontSize}px;`);
    }
    if (styles.fontWeight !== undefined) {
      lines.push(`  font-weight: ${styles.fontWeight};`);
    }
    if (styles.padding !== undefined) {
      lines.push(`  padding: ${styles.padding}px;`);
    }
    if (styles.shadow) {
      const { x, y, blur, color } = styles.shadow;
      lines.push(`  box-shadow: ${x}px ${y}px ${blur}px ${color};`);
    }

    lines.push(`}`);

    return lines.join('\n');
  }

  /**
   * 生成唯一的类名
   */
  private generateUniqueClassName(component: ComponentNode): string {
    return `comp-${component.id}`;
  }

  /**
   * 生成空组件模板
   */
  private generateEmptyTemplate(config: CanvasConfig, options: ExportOptions): string {
    const needsFramerMotion = options.includeAnimation;
    const framerImport = needsFramerMotion ? `\nimport { motion } from 'framer-motion';` : '';

    return `import React from 'react';${framerImport}

const GeneratedPage: React.FC = () => {
  return (
    <div
      className="relative"
      style={{
        width: '${config.width}px',
        height: '${config.height}px',
        backgroundColor: '${config.backgroundColor}',
      }}
    >
      {/* 画布为空 */}
    </div>
  );
};

export default GeneratedPage;`;
  }

  /**
   * 生成 import 语句
   */
  private generateImports(components: ComponentNode[], options: ExportOptions = {}): string {
    const imports: string[] = [`import React from 'react';`];

    // 收集所有组件定义的 imports
    const allImports = new Set<string>();
    for (const component of components) {
      const def = componentRegistry.get(component.type);
      if (def?.codeGen.imports) {
        def.codeGen.imports.forEach(imp => allImports.add(imp));
      }
    }

    // 添加组件定义的 imports
    allImports.forEach(imp => imports.push(imp));

    if (options.includeAnimation) {
      imports.push(`import { motion } from 'framer-motion';`);
    }

    // 去重并返回
    return [...new Set(imports)].join('\n');
  }

  /**
   * 生成组件代码
   */
  private generateComponent(
    components: ComponentNode[],
    config: CanvasConfig,
    options: ExportOptions
  ): string {
    const componentName = 'GeneratedPage';
    const jsx = this.generateJSX(components, options);

    // CSS 模式下需要 import CSS 文件
    const cssImport = options.mode === 'css' ? `\nimport './GeneratedPage.css';` : '';

    return `${cssImport}\n\nconst ${componentName}: React.FC = () => {\n  return (\n    <div\n      className="relative"\n      style={{\n        width: '${config.width}px',\n        height: '${config.height}px',\n        backgroundColor: '${config.backgroundColor}',\n      }}\n    >\n      ${jsx}\n    </div>\n  );\n};`;
  }

  /**
   * 生成 JSX 代码
   */
  private generateJSX(components: ComponentNode[], options: ExportOptions): string {
    // 按 zIndex 排序
    const sortedComponents = [...components].sort((a, b) => a.position.zIndex - b.position.zIndex);

    return sortedComponents
      .map(component => this.generateComponentJSX(component, options))
      .join('\n      ');
  }

  /**
   * 生成单个组件的 JSX
   */
  private generateComponentJSX(component: ComponentNode, options: ExportOptions): string {
    // 预计算 style 与 className（供 Registry 生成器或 fallback 使用）
    const style = options.mode === 'css' ? '{}' : this.generateInlineStyle(component);
    const className =
      options.mode === 'css'
        ? this.generateUniqueClassName(component)
        : this.generateClassName(component);

    // 优先使用 Registry 的代码生成器
    const def = componentRegistry.get(component.type);
    if (def?.codeGen.generateJSX) {
      // 如果有动画，使用 motion.div
      if (options.includeAnimation && component.animation) {
        return this.generateMotionComponent(component, style, className, def.codeGen.generateJSX);
      }

      return def.codeGen.generateJSX(component, style, className);
    }

    // Fallback: 使用内置生成
    if (options.includeAnimation && component.animation) {
      return this.generateMotionComponent(component, style, className, undefined);
    }

    return this.generateBuiltinJSX(component, className, style);
  }

  /**
   * 生成 motion 组件包装
   */
  private generateMotionComponent(
    component: ComponentNode,
    style: string,
    className: string,
    customGenerateJSX?: (component: ComponentNode, style: string, className: string) => string
  ): string {
    const { animation } = component;
    const initial = animation?.initial || {};
    const animate = animation?.animate || {};
    const transition = animation?.transition || {};

    const initialStr = JSON.stringify(initial);
    const animateStr = JSON.stringify(animate);
    const transitionStr = JSON.stringify(transition);

    // 生成内部内容
    const content = customGenerateJSX
      ? customGenerateJSX(component, style, className)
      : this.generateBuiltinJSX(component, className, style);

    return `<motion.div
  initial={${initialStr}}
  animate={${animateStr}}
  transition={${transitionStr}}
>
  ${content}
</motion.div>`;
  }

  /**
   * 生成内置组件的 JSX
   */
  private generateBuiltinJSX(component: ComponentNode, className: string, style: string): string {
    switch (component.type) {
      case 'div':
        return `<div className="${className}" style={${style}} />`;

      case 'button':
        return `<button className="${className}" style={${style}}>${component.content.text || '按钮'}</button>`;

      case 'text':
        return `<p className="${className}" style={${style}}>${component.content.text || '文本内容'}</p>`;

      case 'image':
        return `<img src="${component.content.src || '/placeholder.png'}" alt="${component.content.alt || ''}" className="${className}" style={${style}} />`;

      case 'input':
        return `<input placeholder="${component.content.placeholder || ''}" className="${className}" style={${style}} />`;

      case 'radio':
        return this.generateRadioGroup(component, className, style);

      case 'checkbox':
        return this.generateCheckboxGroup(component, className, style);

      case 'tag':
        return `<span className="${className}" style={${style}}>${component.content.text || '标签'}</span>`;

      default:
        return `<div className="${className}" style={${style}} />`;
    }
  }

  /**
   * 生成单选按钮组
   */
  private generateRadioGroup(component: ComponentNode, className: string, style: string): string {
    const options = component.content.options || [];
    const groupName = `radio-${component.id}`;

    const optionsJSX = options
      .map(option => {
        const checked = option.checked ? ' defaultChecked' : '';
        const disabled = option.disabled ? ' disabled' : '';
        return `<label key="${option.id}" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <input type="radio" name="${groupName}" value="${option.id}"${checked}${disabled} />
          <span>${option.label}</span>
        </label>`;
      })
      .join('\n        ');

    return `<div className="${className}" style={${style}}>
        ${optionsJSX}
      </div>`;
  }

  /**
   * 生成多选按钮组
   */
  private generateCheckboxGroup(
    component: ComponentNode,
    className: string,
    style: string
  ): string {
    const options = component.content.options || [];

    const optionsJSX = options
      .map(option => {
        const checked = option.checked ? ' defaultChecked' : '';
        const disabled = option.disabled ? ' disabled' : '';
        return `<label key="${option.id}" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <input type="checkbox" value="${option.id}"${checked}${disabled} />
          <span>${option.label}</span>
        </label>`;
      })
      .join('\n        ');

    return `<div className="${className}" style={${style}}>
        ${optionsJSX}
      </div>`;
  }

  /**
   * 生成内联样式对象
   */
  private generateInlineStyle(component: ComponentNode): string {
    const { position, styles } = component;

    // 构建样式对象
    const styleObj: Record<string, string | number> = {
      position: 'absolute',
      left: `${position.x}px`,
      top: `${position.y}px`,
      width: `${position.width}px`,
      height: `${position.height}px`,
      zIndex: position.zIndex,
    };

    // 添加可选样式
    if (styles.backgroundColor) {
      styleObj.backgroundColor = styles.backgroundColor;
    }
    if (styles.borderColor) {
      styleObj.borderColor = styles.borderColor;
    }
    if (styles.borderWidth !== undefined) {
      styleObj.borderWidth = `${styles.borderWidth}px`;
      styleObj.borderStyle = 'solid';
    }
    if (styles.borderRadius !== undefined) {
      styleObj.borderRadius = `${styles.borderRadius}px`;
    }
    if (styles.textColor) {
      styleObj.color = styles.textColor;
    }
    if (styles.fontSize !== undefined) {
      styleObj.fontSize = `${styles.fontSize}px`;
    }
    if (styles.fontWeight !== undefined) {
      styleObj.fontWeight = styles.fontWeight;
    }
    if (styles.padding !== undefined) {
      styleObj.padding = `${styles.padding}px`;
    }
    if (styles.shadow) {
      const { x, y, blur, color } = styles.shadow;
      styleObj.boxShadow = `${x}px ${y}px ${blur}px ${color}`;
    }

    // 转换为格式化的 JSON 字符串
    return JSON.stringify(styleObj, null, 2)
      .replace(/\n/g, '\n        ')
      .replace(/^{/, '{\n        ')
      .replace(/}$/, '\n      }');
  }

  /**
   * 生成 Tailwind 类名
   */
  private generateClassName(component: ComponentNode): string {
    const classes: string[] = [];

    if (component.type === 'button') {
      classes.push('cursor-pointer', 'transition-colors');
    }

    if (component.styles.borderRadius !== undefined) {
      const rounded = this.mapBorderRadiusToTailwind(component.styles.borderRadius);
      if (rounded) {
        classes.push(rounded);
      }
    }

    return classes.join(' ');
  }

  /**
   * 映射圆角值到 Tailwind 类名
   */
  private mapBorderRadiusToTailwind(radius: number): string {
    if (radius === 0) return '';
    if (radius <= 2) return 'rounded-sm';
    if (radius <= 4) return 'rounded';
    if (radius <= 6) return 'rounded-md';
    if (radius <= 8) return 'rounded-lg';
    if (radius <= 12) return 'rounded-xl';
    if (radius <= 16) return 'rounded-2xl';
    if (radius <= 24) return 'rounded-3xl';
    return 'rounded-full';
  }

  /**
   * 生成 export 语句
   */
  private generateExports(): string {
    return `export default GeneratedPage;`;
  }
}

/**
 * 导出单例实例
 */
export const codeGenerator = new CodeGenerator();
